[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["KndHvH <delend89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
